package com.zwt.dao;

import com.zwt.dataobject.SequenceDO;
import org.springframework.stereotype.Component;

@Component
public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 15 08:52:48 CST 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 15 08:52:48 CST 2022
     */
    int insert(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 15 08:52:48 CST 2022
     */
    int insertSelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 15 08:52:48 CST 2022
     */
    SequenceDO selectByPrimaryKey(String name);

    SequenceDO getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 15 08:52:48 CST 2022
     */
    int updateByPrimaryKeySelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 15 08:52:48 CST 2022
     */
    int updateByPrimaryKey(SequenceDO row);
}